// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Categories documents
 */
interface CategoriesDocumentData {
  /**
   * Title field in *Categories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categories.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Categories document from Prismic
 *
 * - **API ID**: `categories`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoriesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoriesDocumentData>,
    "categories",
    Lang
  >;

/**
 * Content for Faq documents
 */
interface FaqDocumentData {
  /**
   * question field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * answer field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.answer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer: prismic.KeyTextField;
}

/**
 * Faq document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FaqDocumentData>, "faq", Lang>;

/**
 * Item in *Featured Projects → Featured Projects*
 */
export interface FeaturedProjectsDocumentDataFeaturedProjectsItem {
  /**
   * Project field in *Featured Projects → Featured Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_projects.featured_projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"projects">;
}

/**
 * Content for Featured Projects documents
 */
interface FeaturedProjectsDocumentData {
  /**
   * Featured Projects field in *Featured Projects*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_projects.featured_projects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featured_projects: prismic.GroupField<
    Simplify<FeaturedProjectsDocumentDataFeaturedProjectsItem>
  >;
}

/**
 * Featured Projects document from Prismic
 *
 * - **API ID**: `featured_projects`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FeaturedProjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FeaturedProjectsDocumentData>,
    "featured_projects",
    Lang
  >;

/**
 * Item in *Gallery Types → Gallery*
 */
export interface GalleryTypesDocumentDataGalleryItem {
  /**
   * image field in *Gallery Types → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_types.gallery[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Gallery Types documents
 */
interface GalleryTypesDocumentData {
  /**
   * Title field in *Gallery Types*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_types.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Gallery Types*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_types.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Gallery field in *Gallery Types*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_types.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<GalleryTypesDocumentDataGalleryItem>>;

  /**
   * Theme field in *Gallery Types*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_types.theme
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  theme: prismic.ColorField;
}

/**
 * Gallery Types document from Prismic
 *
 * - **API ID**: `gallery_types`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryTypesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<GalleryTypesDocumentData>,
    "gallery_types",
    Lang
  >;

/**
 * Content for Homepage Image Collage documents
 */
interface HomepageImageCollageDocumentData {
  /**
   * left field in *Homepage Image Collage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_image_collage.left
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  left: prismic.ImageField<never>;

  /**
   * center field in *Homepage Image Collage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_image_collage.center
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  center: prismic.ImageField<never>;

  /**
   * right field in *Homepage Image Collage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_image_collage.right
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  right: prismic.ImageField<never>;
}

/**
 * Homepage Image Collage document from Prismic
 *
 * - **API ID**: `homepage_image_collage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageImageCollageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageImageCollageDocumentData>,
    "homepage_image_collage",
    Lang
  >;

/**
 * Item in *Projects → Gallery*
 */
export interface ProjectsDocumentDataGalleryItem {
  /**
   * Image field in *Projects → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.gallery[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Projects documents
 */
interface ProjectsDocumentData {
  /**
   * Title	 field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Cover Image field in *Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Gallery field in *Projects*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<ProjectsDocumentDataGalleryItem>>;

  /**
   * Category	 field in *Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"categories">;

  /**
   * Location field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Date field in *Projects*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Client field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.client
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  client: prismic.KeyTextField;
}

/**
 * Projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectsDocumentData>,
    "projects",
    Lang
  >;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
  /**
   * Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Feature Image field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.feature_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  feature_image: prismic.ImageField<never>;

  /**
   * Description field in *Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;

/**
 * Item in *Slider → sliders*
 */
export interface SliderDocumentDataSlidersItem {
  /**
   * image field in *Slider → sliders*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.sliders[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Slider documents
 */
interface SliderDocumentData {
  /**
   * sliders field in *Slider*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.sliders[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sliders: prismic.GroupField<Simplify<SliderDocumentDataSlidersItem>>;
}

/**
 * Slider document from Prismic
 *
 * - **API ID**: `slider`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SliderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SliderDocumentData>,
    "slider",
    Lang
  >;

/**
 * Item in *Stats images → group one*
 */
export interface StatsImagesDocumentDataGroupOneItem {
  /**
   * images field in *Stats images → group one*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_images.group_one[].images
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  images: prismic.ImageField<never>;
}

/**
 * Content for Stats images documents
 */
interface StatsImagesDocumentData {
  /**
   * group one field in *Stats images*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_images.group_one[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group_one: prismic.GroupField<Simplify<StatsImagesDocumentDataGroupOneItem>>;

  /**
   * Feature Image field in *Stats images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_images.feature_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  feature_image: prismic.ImageField<never>;
}

/**
 * Stats images document from Prismic
 *
 * - **API ID**: `stats_images`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StatsImagesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<StatsImagesDocumentData>,
    "stats_images",
    Lang
  >;

/**
 * Item in *Story Teller → images*
 */
export interface StoryTellerDocumentDataImagesItem {
  /**
   * image field in *Story Teller → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story_teller.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Story Teller documents
 */
interface StoryTellerDocumentData {
  /**
   * images field in *Story Teller*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: story_teller.images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<StoryTellerDocumentDataImagesItem>>;
}

/**
 * Story Teller document from Prismic
 *
 * - **API ID**: `story_teller`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StoryTellerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<StoryTellerDocumentData>,
    "story_teller",
    Lang
  >;

export type AllDocumentTypes =
  | CategoriesDocument
  | FaqDocument
  | FeaturedProjectsDocument
  | GalleryTypesDocument
  | HomepageImageCollageDocument
  | ProjectsDocument
  | ServicesDocument
  | SliderDocument
  | StatsImagesDocument
  | StoryTellerDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CategoriesDocument,
      CategoriesDocumentData,
      FaqDocument,
      FaqDocumentData,
      FeaturedProjectsDocument,
      FeaturedProjectsDocumentData,
      FeaturedProjectsDocumentDataFeaturedProjectsItem,
      GalleryTypesDocument,
      GalleryTypesDocumentData,
      GalleryTypesDocumentDataGalleryItem,
      HomepageImageCollageDocument,
      HomepageImageCollageDocumentData,
      ProjectsDocument,
      ProjectsDocumentData,
      ProjectsDocumentDataGalleryItem,
      ServicesDocument,
      ServicesDocumentData,
      SliderDocument,
      SliderDocumentData,
      SliderDocumentDataSlidersItem,
      StatsImagesDocument,
      StatsImagesDocumentData,
      StatsImagesDocumentDataGroupOneItem,
      StoryTellerDocument,
      StoryTellerDocumentData,
      StoryTellerDocumentDataImagesItem,
      AllDocumentTypes,
    };
  }
}
